[package]
name = "nself-app"
version = "0.1.0"
description = "Cross-platform nSelf application"
authors = []
license = ""
repository = ""
edition = "2021"
rust-version = "1.60"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.6", features = ["dialog-all", "fs-all", "path-all", "notification-all", "clipboard-all", "shell-open", "window-all"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
